spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/simple_board?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!!

# 서버 설정
server:
  port: 8080

# 로깅 설정
logging:
  level:
    com.example.simple_board: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
